name: "NodeJS API Integration Test CI"

on:
  push:
    branches: 
      - main

jobs:
  push-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: NodeJS Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'                       # Use a stable LTS version of Node.js

      - name: Install dependencies and run the server
        run: |
          npm install
          npm install -g newman
          nohup node server.js &

      - name: Wait for server to start
        run: sleep 5                               # Adjust if necessary to give the server time to initialize

      - name: Run integration tests with Newman
        run: |
          newman run simple-api-tests.json

      # Stop the server after tests
      - name: Stop the server
        run: |                                     # Kill the server running on port 3000 (adjust port if necessary)
          kill $(lsof -t -i:3000) 
